name = "Cliques"
uuid = "419091ed-972f-4654-a321-b0a63cbf78f4"
version = "0.1.0"
authors = ["Waylon Wu <waylon_wu@outlook.com>"]

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[compat]
Distributed = "1.11.0"
Random = "1.11.0"
StyledStrings = "1.11.0"
